In [ ]:
from girder_functions import *
import numpy as np
# turns = np.round(np.random.uniform(-5, 5, 6) / 0.25) * 0.25
# turns.tolist()
turns = [-3,2,3,-1,3,2]
final_pos = move_girder(turns)
print(f'final position is:{final_pos}')

w1,w2,w3 = move_girder_inv(final_pos)
print(w1,w2,w3)
final_pos = move_girder([0,0,0,w1,w2,w3])
print(f'final position is:{final_pos}')

final position is:[ 0.4188436   0.07467242 -1.03522224 -0.00111064 -0.01041687  0.0014005 ]
0.7616205525480849 0.874899030302438 0.5891703327231097
final position is:[-2.43764190e-03  7.46724128e-02 -6.50741411e-02 -3.17434800e-04
  0.00000000e+00 -1.18909000e-05]


In [63]:
(13*4)**6

19770609664

In [52]:
magnet_c = np.array([[0],[205],[0],[1]])
(trans_w3(2) @ trans_w2(3) @ trans_w1(-1)@ magnet_c) - magnet_c

array([[ 0.28700196],
       [ 0.07467252],
       [-0.22762511],
       [ 0.        ]])

In [53]:
magnet_c = np.array([[0],[205],[0],[1]])
(trans_w2(7) @ trans_w3(5) @ trans_w1(0)@ magnet_c) - magnet_c

array([[ 0.49235735],
       [ 0.29889966],
       [-0.45685848],
       [ 0.        ]])

In [54]:
turns = move_girder_inv(final_pos)

change_wedge(turns)


array([ 7.46724065e-02, -3.17633500e-04, -1.17821000e-05])

In [55]:
w1,w2,w3 = 0,0,10
magnet_b = np.array([[0],[0],[0],[1]])
magnet_c = np.array([[0],[205],[0],[1]])
# m_c_l3 = trans_w1(w1) @ trans_w3(w3) @ trans_w2(w2) @  magnet_c
# m_b_l3 = trans_w1(w1) @ trans_w3(w3) @ trans_w2(w2)  @ magnet_b
m_b_l3 = trans_w3(w3) @ magnet_b
print(m_b_l3)

# delta_x = np.round(m_c_l3[0,0],10)
# delta_y = np.round(m_b_l3[1,0],10)
# delta_z = np.round(m_c_l3[2,0],10)
# pitch =  np.round(m_c_l3[2,0]/205,10) # around x 
# roll =   np.round(m_c_l3[0,0]/205,10) # around z
# print(delta_x,delta_y,delta_z,pitch,roll)

[[2.49997345e-04]
 [2.49994689e-01]
 [1.38887414e-03]
 [1.00000000e+00]]


In [56]:
w1,w2,w3 = -5,5,5
magnet_b = np.array([[0],[0],[0],[1]])
magnet_c = np.array([[0],[205],[0],[1]])
m_c_l3 = trans_w2(w2) @ trans_w3(w3) @ trans_w1(w1) @ magnet_c
m_b_l3 = trans_w2(w2) @ trans_w3(w3) @ trans_w1(w1) @ magnet_b
delta_x = np.round(m_c_l3[0,0],10)
delta_y = np.round(m_b_l3[1,0],10)
delta_z = np.round(m_c_l3[2,0],10)
pitch =  np.round(m_c_l3[2,0]/205,10) # around x 
roll =   np.round(m_c_l3[0,0]/205,10) # around 
print(delta_x)

0.8194957074


In [57]:
from girder_functions import *
import numpy as np
# turns = np.round(np.random.uniform(-5, 5, 6) / 0.25) * 0.25
# turns.tolist()
turns = [ 2,2,-3,-1,3,2 ]
final_pos = move_girder(turns)
print(final_pos)
# turns_guess = move_girder_inv(final_pos)
# turns_guess_rounded = np.round(move_girder_inv(final_pos)/0.25)*0.25
# print(turns)
# print(turns_guess)
# print(turns_guess_rounded)
# final_pos_guess = move_girder(turns_guess)
# final_pos_guess_rounded = move_girder(turns_guess_rounded)

# # Calculate the errors in millimeters (multiplied by 1000)
# errors = [(final - guess) * 1000 for final, guess in zip(final_pos, final_pos_guess)]
# print(errors)
# # Check if any error is above 50 and print a message if true
# if any(error > 50 for error in errors):
#     print("Tolerance reached")
# print('_'*50)
# var_names = ['dx','dy','dz','pitch','yaw','roll']
# # Calculate the errors in millimeters (multiplied by 1000)
# errors = [(final - guess) * 1000 for final, guess in zip(final_pos, final_pos_guess_rounded)]
# # Check if any error is above 50 and print a message if true
# if any(abs(error) > 20 for error in errors):
#     print("Above the Tolerance limit !!!")
#     for i,error in enumerate(errors):
#         print(f'{var_names[i]} : {error}')




[-0.21022374  0.07467242 -0.97886687 -0.00111064  0.          0.0014005 ]


In [58]:
print(turns_guess)
print(turns_guess_rounded)
final_pos_guess = move_girder(turns_guess)
final_pos_guess_rounded = move_girder(turns_guess_rounded)

# Calculate the errors in millimeters (multiplied by 1000)
errors = [(final - guess) * 1000 for final, guess in zip(final_pos, final_pos_guess)]
print(errors)
# Check if any error is above 50 and print a message if true
if any(error > 50 for error in errors):
    print("Tolerance reached")
print('_'*50)
var_names = ['dx','dy','dz','pitch','yaw','roll']
# Calculate the errors in millimeters (multiplied by 1000)
errors = [(final - guess) * 1000 for final, guess in zip(final_pos, final_pos_guess_rounded)]
# Check if any error is above 50 and print a message if true
if any(abs(error) > 20 for error in errors):
    print("Above the Tolerance limit !!!")
    for i,error in enumerate(errors):
        print(f'{var_names[i]} : {error}')


NameError: name 'turns_guess' is not defined